version: '3.6'
services:
  postgres:
    build: postgres-with-pgloader
    container_name: postgres-db
    ports:
      - '5431:5432'
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'pgadmin4@pgadmin.org'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - '5050:80'
    depends_on:
      - postgres

  mysql:
    image: mysql:5.7
    container_name: mysql-db
    ports:
      - '3307:3306'
    volumes:
      - /var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - '8080:8080'
    depends_on:
      - mysql

  mssql:
    image: mcr.microsoft.com/mssql/server
    container_name: mssql-db
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"

volumes:
  db_data:
